[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  // LibGDX core library
  api("com.badlogicgames.gdx:gdx:$gdxVersion")

  // Ashley for our ECS architecture
  api("com.badlogicgames.ashley:ashley:$ashleyVersion")

  // A few essential KTX (Kotlin Extensions) libraries to make life easier
  api("io.github.libktx:ktx-app:$ktxVersion")       // For screens, application listeners
  api("io.github.libktx:ktx-ashley:$ktxVersion")    // Helpers for Ashley
  api("io.github.libktx:ktx-graphics:$ktxVersion")  // Graphics helpers

  // The Kotlin standard library
  api("org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion")
}
